[package]
name = "pki-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.27", features = ["derive"] }
const-oid = { version = "0.9.1", features = ["db"] }
knuffel = "2.0.0"
miette = { version = "4.3.0", features = ["fancy"] }
pkcs8 = { version = "0.9.0", features = ["pem"] }
rand = "0.8.5"
rsa = "0.7.2"
x509-cert = "0.1.0"
zeroize = "1.5.7"
